//! Host trait implementations for the policy's WIT imports.
//!
//! Each submodule attaches `Host` traits generated by `bindgen!` to
//! [`crate::state::HostState`]:
//!
//!   * [`disclosure`] — `prompt_disclosure` (consent screen).
//!   * [`media`] — `prompt_media`, `prompt_any_of` (capture flows).
//!   * [`embedded`] — `disclosure_field`, `localized` (text-ref
//!     resolution for both `enclavid:embedded/*` interfaces;
//!     currently passthrough stubs).
//!
//! These impls are reachable only via the policy's
//! [shim Linker](crate::intercept::shim) — which wraps each
//! registration so every host call gets intercept + replay treatment
//! before reaching the function body here. Plugins live in their own
//! Stores with an empty Linker and cannot reach these impls.

pub(crate) mod disclosure;
pub(crate) mod embedded;
pub(crate) mod media;
