//! Host trait implementations for the policy's suspending WIT
//! imports — `prompt_disclosure` and `prompt_media` / `prompt_any_of`.
//!
//! Each submodule attaches `Host` traits generated by `bindgen!` to
//! [`crate::state::HostState`]:
//!
//!   * [`disclosure`] — `prompt_disclosure` (consent screen).
//!   * [`media`] — `prompt_media`, `prompt_any_of` (capture flows).
//!
//! `enclavid:embedded/*` host fns live in [`crate::embedded::host`]
//! alongside the rest of the embedded-section machinery, not here —
//! they don't suspend, don't touch the replay log, and share data
//! structures (slot model, registry) with the embedded-loader.
//!
//! These impls are reachable only via the policy's
//! [shim Linker](crate::intercept::shim) — which wraps each
//! registration so every host call gets intercept + replay treatment
//! before reaching the function body here. Plugins live in their own
//! Stores and reach only the embedded interfaces (via
//! [`crate::embedded::register_for_slot`]).

pub(crate) mod disclosure;
pub(crate) mod media;
