[workspace]
resolver = "2"
members = [
    "crates/api",
    "crates/attestation",
    "crates/host-hatch",
    "crates/host-relay",
    "crates/hatch-protocol",
    "crates/cli",
    "crates/engine-compiler",
    "crates/engine-compiler-child",
    "crates/engine-executor",
    "crates/engine-executor-child",
    "crates/engine-types",
    "crates/hatch-client",
    "crates/engine-supervisor",
    "crates/boundary",
    "crates/crypto",
    "crates/embedded",
    "crates/kbs-client",
    "crates/engine-rpc",
    "crates/fleet-transport",
    "crates/safe-logger",
    "crates/ra-tls",
    "crates/storage-rpc",
    "crates/storage",
    "xtask",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/enclavid/enclavid"
