//! The applicant's page, as it sits inside this binary.
//!
//! The table is generated by `build.rs` from the built `frontend/`, so the bytes
//! a browser runs are part of this role's launch digest — the same digest that
//! covers the handlers the page calls.
//!
//! A developer build has an empty table and says 404. Vite serves the page on
//! its own port there, which is what `frontend/vite.config.ts` is arranged for.

/// One file, and what to say it is.
pub struct Asset {
    /// The request path this answers to, with a leading slash.
    pub path: &'static str,
    pub content_type: &'static str,
    pub bytes: &'static [u8],
}

include!(concat!(env!("OUT_DIR"), "/assets.rs"));

/// The document, served at `/` and at a session's own path.
const INDEX: &str = "/index.html";

/// The prefix Vite gives content-addressed output. A file under it is named by
/// a hash of what is in it, so its name changes whenever its bytes do.
const IMMUTABLE_PREFIX: &str = "/assets/";

/// The asset for a request path: the file at it, or the document.
///
/// The document answers at `/`, where a link that names no session lands, and
/// at `/<session id>`, the link to one session — `/ses_` and hex, one segment,
/// so the page sits at the same depth either way and what it loads resolves
/// beside it. Nothing else resolves to the document: a page served deeper
/// would resolve what it loads relatively under that path, and be handed the
/// document again for each of those — a page that loads and runs nothing, with
/// no error to say why. A path that is no file is nothing, and the caller
/// answers 404.
pub fn lookup(path: &str) -> Option<&'static Asset> {
    if path == "/" || names_a_session(path) {
        exact(INDEX)
    } else {
        exact(path)
    }
}

/// Whether `path` is a session's link: `/ses_` and lowercase hex, nothing after.
fn names_a_session(path: &str) -> bool {
    path.strip_prefix("/ses_").is_some_and(|hex| {
        !hex.is_empty()
            && hex
                .bytes()
                .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
    })
}

fn exact(path: &str) -> Option<&'static Asset> {
    ASSETS.iter().find(|asset| asset.path == path)
}

/// How long a browser may keep this file.
///
/// Content-addressed output can be kept for ever, because a change to it is a
/// change of name. The document cannot be kept at all: it is the thing that
/// names the current build's files, and a stale one points at files that are
/// gone. `no-store` rather than `no-cache`, so it is not written down either —
/// this is an applicant's device, and the page is about them.
pub fn cache_control(asset: &Asset) -> &'static str {
    if asset.path.starts_with(IMMUTABLE_PREFIX) {
        "public, max-age=31536000, immutable"
    } else {
        "no-store"
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The table is whatever the build was given, so what is asserted here is
    /// the RULE, not its contents — and the rule has to hold for an empty table
    /// too, which is what a developer build has.
    #[test]
    fn an_empty_table_resolves_nothing() {
        if ASSETS.is_empty() {
            assert!(lookup("/").is_none());
            assert!(lookup("/no/such/page").is_none());
        }
    }

    /// The document is served at `/` and at a session's link, and at no other
    /// path that is not a file — checked wherever a document exists.
    #[test]
    fn the_document_is_served_at_the_root_and_a_sessions_link_alone() {
        if exact(INDEX).is_some() {
            assert_eq!(lookup("/").expect("the document").path, INDEX);
            assert_eq!(lookup("/ses_0a1f").expect("a session's link").path, INDEX);
            assert!(lookup("/no/such/page").is_none());
            assert!(lookup("/session/ses_ab/assets/index.js").is_none());
        }
    }

    /// One segment of `ses_` and lowercase hex, and nothing more — a deeper or
    /// trailing path would move what the page loads out from beside it.
    #[test]
    fn a_sessions_link_is_one_segment_of_its_id() {
        assert!(names_a_session("/ses_0a1f"));
        for not in [
            "/ses_",
            "/ses_0A1F",
            "/ses_0a1f/",
            "/ses_0a1f/start",
            "/x/ses_0a1f",
            "/ses_zz",
            "ses_0a1f",
        ] {
            assert!(!names_a_session(not), "{not}");
        }
    }

    /// The two cache answers, on paths rather than on a table that may be empty.
    #[test]
    fn only_content_addressed_output_may_be_kept() {
        let hashed = Asset {
            path: "/assets/index-abc123.js",
            content_type: "text/javascript; charset=utf-8",
            bytes: b"",
        };
        let document = Asset {
            path: "/index.html",
            content_type: "text/html; charset=utf-8",
            bytes: b"",
        };
        assert!(cache_control(&hashed).contains("immutable"));
        assert_eq!(cache_control(&document), "no-store");
    }
}
