//! The applicant's page, as it sits inside this binary.
//!
//! The table is generated by `build.rs` from the built `frontend/`, so the bytes
//! a browser runs are part of this role's launch digest — the same digest that
//! covers the handlers the page calls.
//!
//! A developer build has an empty table and says 404. Vite serves the page on
//! its own port there, which is what `frontend/vite.config.ts` is arranged for.

/// One file, and what to say it is.
pub struct Asset {
    /// The request path this answers to, with a leading slash.
    pub path: &'static str,
    pub content_type: &'static str,
    pub bytes: &'static [u8],
}

include!(concat!(env!("OUT_DIR"), "/assets.rs"));

/// The document every unrecognised path falls back to.
const INDEX: &str = "/index.html";

/// The prefix Vite gives content-addressed output. A file under it is named by
/// a hash of what is in it, so its name changes whenever its bytes do.
const IMMUTABLE_PREFIX: &str = "/assets/";

/// The asset for a request path, following the single-page rule.
///
/// An unmatched path resolves to the document rather than to nothing, because
/// the routes a person sees — `/session/<id>/…` — exist only inside the page and
/// have no file behind them. The cost is the one the gateway notes record: an
/// address that means nothing renders the shell with a 200 rather than an error,
/// and the page is what has to say so.
///
/// `/` resolves to the document too, which is the same rule and not a special
/// case: there is no file at `/`.
pub fn lookup(path: &str) -> Option<&'static Asset> {
    exact(path).or_else(|| exact(INDEX))
}

fn exact(path: &str) -> Option<&'static Asset> {
    ASSETS.iter().find(|asset| asset.path == path)
}

/// How long a browser may keep this file.
///
/// Content-addressed output can be kept for ever, because a change to it is a
/// change of name. The document cannot be kept at all: it is the thing that
/// names the current build's files, and a stale one points at files that are
/// gone. `no-store` rather than `no-cache`, so it is not written down either —
/// this is an applicant's device, and the page is about them.
pub fn cache_control(asset: &Asset) -> &'static str {
    if asset.path.starts_with(IMMUTABLE_PREFIX) {
        "public, max-age=31536000, immutable"
    } else {
        "no-store"
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The table is whatever the build was given, so what is asserted here is
    /// the RULE, not its contents — and the rule has to hold for an empty table
    /// too, which is what a developer build has.
    #[test]
    fn an_empty_table_resolves_nothing() {
        if ASSETS.is_empty() {
            assert!(lookup("/").is_none());
            assert!(lookup("/session/abc").is_none());
        }
    }

    /// Falling back to the document is what makes the in-page routes work, so
    /// it is checked wherever a document exists.
    #[test]
    fn an_unknown_path_falls_back_to_the_document() {
        if exact(INDEX).is_some() {
            let fallback = lookup("/session/abc/step/2").expect("the document");
            assert_eq!(fallback.path, INDEX);
            assert_eq!(lookup("/").expect("the document").path, INDEX);
        }
    }

    /// The two cache answers, on paths rather than on a table that may be empty.
    #[test]
    fn only_content_addressed_output_may_be_kept() {
        let hashed = Asset {
            path: "/assets/index-abc123.js",
            content_type: "text/javascript; charset=utf-8",
            bytes: b"",
        };
        let document = Asset {
            path: "/index.html",
            content_type: "text/html; charset=utf-8",
            bytes: b"",
        };
        assert!(cache_control(&hashed).contains("immutable"));
        assert_eq!(cache_control(&document), "no-store");
    }
}
