use anyhow::Result;
use clap::{Parser, Subcommand};
use std::path::PathBuf;

mod auth;
mod commands;
mod config;
mod discovery;
mod policy_manifest;

#[derive(Parser)]
#[command(name = "enclavid")]
#[command(about = "Manage Enclavid policies — encrypt, push, and authenticate", long_about = None)]
#[command(version)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Authenticate to Enclavid (interactive, opens browser)
    Login,

    /// Remove locally-stored credentials
    Logout,

    /// Print a fresh access token to stdout (for piping into oras login etc.)
    Token,

    /// Generate a new K_client encryption key
    Keygen {
        /// Output path for the key file
        #[arg(short, long, default_value = "client.key")]
        output: PathBuf,
    },

    /// Encrypt a wasm policy with a K_client key
    Encrypt {
        /// Path to plaintext wasm file
        wasm: PathBuf,

        /// Path to K_client key file (generated by `enclavid keygen`)
        #[arg(short, long)]
        key: PathBuf,

        /// Output path for encrypted artifact
        #[arg(short, long)]
        output: Option<PathBuf>,
    },

    /// Push an encrypted policy to an OCI registry
    Push {
        /// Path to encrypted artifact (.wasm.age)
        artifact: PathBuf,

        /// Full OCI reference: `<registry>/<repository>[:tag]`. Examples:
        /// `registry.enclavid.com/acme/kyc:v1`,
        /// `ghcr.io/acme/policies/kyc:latest`. Tag defaults to a
        /// timestamp if omitted; the artifact is also re-tagged as
        /// `:latest` unless that's already the supplied tag.
        reference: String,

        /// Path to the K_client file used to encrypt this artifact.
        /// Used to mint the manifest validator annotation that
        /// `POST /api/v1/sessions` checks before storing K_client.
        #[arg(short = 'k', long = "key")]
        key: PathBuf,

        /// Path to the polici manifest JSON file. Bundled as the
        /// second OCI layer (plain, not encrypted). Point to a
        /// missing file if the polici has no host-visible UI
        /// (decision-only stubs).
        #[arg(short = 'm', long = "manifest", default_value = "policy.json")]
        manifest: PathBuf,
    },

    /// Validate a polici manifest against the same rules the TEE
    /// engine enforces at load time. Run before `push` to catch
    /// issues at author time with clean error messages.
    Validate {
        /// Path to the manifest file (default: `./policy.json`).
        #[arg(default_value = "policy.json")]
        path: PathBuf,
    },
}

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "enclavid=info".into()),
        )
        .init();

    let cli = Cli::parse();

    let needs_discovery = !matches!(
        cli.command,
        Commands::Keygen { .. }
            | Commands::Encrypt { .. }
            | Commands::Validate { .. }
            | Commands::Logout
    );
    if needs_discovery {
        discovery::load().await?;
    }

    match cli.command {
        Commands::Login => commands::login::run().await,
        Commands::Logout => commands::logout::run().await,
        Commands::Token => commands::token::run().await,
        Commands::Keygen { output } => commands::keygen::run(output),
        Commands::Encrypt { wasm, key, output } => commands::encrypt::run(wasm, key, output),
        Commands::Push {
            artifact,
            reference,
            key,
            manifest,
        } => commands::push::run(artifact, reference, key, manifest).await,
        Commands::Validate { path } => commands::validate::run(path).await,
    }
}
