package enclavid:disclosure;

interface disclosure {
    record display-field {
        label: string,
        value: string,
    }

    prompt-disclosure: func(fields: list<display-field>) -> bool;
}
